version: "3"

networks:
  loki:

services:
  loki:
    image: grafana/loki:2.9.2
    volumes:
      - "./loki-config.yaml:/etc/loki/local-config.yaml"
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki

  promtail:
    image: grafana/promtail:2.9.2
    volumes:
      - /var/log:/var/log
      - /root/.pm2/logs:/root/.pm2/logs
      - "./promtail-config.yaml:/etc/promtail/config.yaml"
    command: -config.file=/etc/promtail/config.yaml
    networks:
      - loki
